name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Setup Ruby environment with ruby-build
      uses: clupprich/ruby-build-action@v1.3.0
      with:
        # Ruby version
        ruby-version: 2.6.1
        # Flag if the Ruby installation is cached
        cache-available: false
